<a href="https://colab.research.google.com/github/takatoshiinaoka/-pattern_recognition/blob/main/%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3%E8%AA%8D%E8%AD%984.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# パターン認識
## 第4回：パターン認識(3章後半)


### 各層における伝達信号の実装

In [18]:
import numpy as np
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B1 = np.array([0.1, 0.2, 0.3])
B2 = np.array([0.1, 0.2])
B3 = np.array([0.1, 0.2])

print(X.shape)
print(W1.shape)
print(W2.shape)
print(W3.shape)
print(B1.shape)
print(B2.shape)
print(B3.shape)
print()

#シグモイド関数
def sigmoid(x):
  return 1/(1+np.exp(-x))

#恒等関数
def identity_function(x): 
  return x  #今回は何の計算もしていない[目的によって変わる]

#1層目の計算
A1 = np.dot(X, W1) + B1
Z1 = sigmoid(A1) 
print(str(A1) +"\n"+ str(Z1), end="\n\n")

#2層目の計算
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2) 
print(str(A2) +"\n"+ str(Z2), end="\n\n")

#3層目の計算
A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3) 
print(str(A3) +"\n"+ str(Y), end="\n\n")

(2,)
(2, 3)
(3, 2)
(2, 2)
(3,)
(2,)
(2,)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]

[0.51615984 1.21402696]
[0.62624937 0.7710107 ]

[0.31682708 0.69627909]
[0.31682708 0.69627909]



### 実装まとめ

In [24]:
import numpy as np

def sigmoid(x):
  return 1/(1+np.exp(-x))

def identity_function(x): 
  return x  

def softmax(a):
  exp_a = np.exp(a)
  sum_exp_a = np.sum(exp_a)
  y = exp_a/sum_exp_a
  return y

def init_network(): #重みとバイアスの初期化
  network = {} 
  network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
  network['b1'] = np.array([0.1, 0.2, 0.3])
  network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
  network['b2'] = np.array([0.1, 0.2])
  network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
  network['b3'] = np.array([0.1, 0.2])

  return network
  
def forwarod(network, x): #前向きの伝達情報. 後ろで,後ろ向きの学習がある.
  W1, W2, W3 = network['W1'], network['W2'], network['W3']
  b1, b2, b3 = network['b1'], network['b2'], network['b3']

  a1 = np.dot(x, W1) + b1
  z1 = sigmoid(a1) 
  a2 = np.dot(z1, W2) + b2
  z2 = sigmoid(a2) 
  a3 = np.dot(z2, W3) + b3
  y = identity_function(a3) 

  return y

network = init_network()
x = np.array([1.0, 0.5])   #入力でーた
y = forwarod(network, x)  #出力データ
print(y)

[0.31682708 0.69627909]


### 出力層の設計
- 分類問題
  - データがどのクラスに属するか  
  例：写真の人物は男か？女か？
  - 活性化関数としてソフトマックス関数を使う　　

  ```
  def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a/sum_exp_a
    return y
  ```
- 回帰問題
  - データから,別の数値を予想  
  例：写真の人物の体重は？
  - 活性化関数として恒等関数を使う  
  
  ```
  def identity_function(x): 
    return x  
  ```

In [25]:
import numpy as np

def softmax(a):
  exp_a = np.exp(a)
  sum_exp_a = np.sum(exp_a)
  y = exp_a/sum_exp_a
  return y

a = np.array([0.3, 2.9, 4.0])
softmax(a)

array([0.01821127, 0.24519181, 0.73659691])

### ソフトマックス関数の特徴
- オーバーフローに注意

In [35]:
import numpy as np

def softmax(a):
  c = np.max(a)
  exp_a = np.exp(a - c)
  sum_exp_a = np.sum(exp_a)
  y = exp_a/sum_exp_a
  return y

a = np.array([0.3, 2.9, 4.0])
softmax(a)

array([0.01821127, 0.24519181, 0.73659691])

### 出力層ニューロンの数
- 解くべき問題に応じて決める
- 例：手書きの数字を認識する
  - 数字は0~9の10個 = 10クラス

### 手書き数字認識
- 手書き数字画像を分類する  
ニューラルネットを作る
- 重みなどのパラメータは？
  - 実際は学習で求める
  - 今回は学習済みのパラメータを使用
- 認識処理(推論処理)はニューラルネットの順方向伝播  
forward propagation


### MNISTデータセット
- 手書き数字の有名なデータセット
- 0~9の数字画像
  - 訓練用画像：60,000枚
  - テスト用画像：10,000枚
  - 28×28ピクセルのグレー画像
  - 各ビクセルは0~255の値

### ニューラルネットワークの推論処理
- ニューラルネットの構成
  - 入力層：784ニューロン(28×28ピクセル)
  - 出力層：10ニューロン(0~9の10クラス)
  - 隠れ層：経験から決める(変更可)
    - 1つ目：50ニューロン 
    - 2つ目：100ニューロン

In [ ]:
# mnist_show.py
import sys, os
sys.path.append(os.pardir)
import numpy as np
from dataset.mnist import load_mnist
from PIL import Image

def img_show(img):
  pil_img = Image.fromarray(np.uint8(img))
  pil_img.show()

(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, flatten=True, one_hot_label=False)

img = x_train[0]
label = t_tarain[0]
print(label) #5

print(img.shape) #(784,)
img = img.reshape(28, 28) #形状を元の画像サイズに変換
print(img.shape)

img.show()


In [ ]:
#neuralnet_mnist.py
import sys, os
sys.path.append(os.pardir) #親ディレクトファイルをインポートするための設定
import numpy as np
import pickle
from dataset.mnist import load_mnist
from common.functions import sigmoid, softmax


def get_data():
  (x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, flatten=True, one_hot_label=False)
  return x_test, t_test

def init_network():
  with open("sample_weight.pkl", 'rb') as f:
    network = pickle.load(f)
    return network

def predict(network, x):
  W1, W2, W3 = network['W1'], network['W2'], network['W3']
  b1, b2, b3 = network['b1'], network['b2'], network['b3']

  a1 = np.dot(x, W1) + b1
  z1 = sigmoid(a1) 
  a2 = np.dot(z1, W2) + b2
  z2 = sigmoid(a2) 
  a3 = np.dot(z2, W3) + b3
  y = softmax(a3) 

  return y

  x, t = get_data()
  network = init_network()

  accuracy_cnt = 0
  for i in range(len(x)):  
    y = predict(network, x[i])
    p = np.argmax(y)  #最も確率の高い要素のインデックスを取得
    if p == t[i]:
      accuracy_cnt += 1 #正解数をカウント

  print("Accuracy：" + str(float(accuracy_cnt)/len(x)))


### バッチ処理
- 1枚の画像(28×28=784ピクセル)からどの数字か認識


|  x | w1 | w2 | w3 | Y |
| ---- | ---- | ---- | ---- | ---- |
| 784 | 784*50 | 50*100 | 100*10 | 10 |


- 100枚の画像の写真からそれぞれどの数字か認識


|  x | w1 | w2 | w3 | Y |
| ---- | ---- | ---- | ---- | ---- |
| 100*784 | 784*50 | 50*100 | 100*10 | 10 |


In [ ]:
x, t = get_data()
network = init_network()

batch_size = 100 #バッチの数
accuracy_cnt = 0

for i in range(0, len(x), batch_size):
  x_batch = x[i : i+batch_size] #入力データを100枚づつまとめる
  y_batch = predict(network, x_batch)
  p = np.argmax(y_batch, axis=1)
  accuracy_cnt += np.sum(p == t[i:i+batch_size]) #正しい答えの数をカウント

print("Accuracy：" + str(float(accuracy_cnt)/len(x)))